// Code generated by MockGen. DO NOT EDIT.
// Source: friend_list_controller.go

// Package mock_controller is a generated GoMock package.
package mock_controller

import (
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
	echo "github.com/labstack/echo/v4"
)

// MockFriendListController is a mock of FriendListController interface.
type MockFriendListController struct {
	ctrl     *gomock.Controller
	recorder *MockFriendListControllerMockRecorder
}

// MockFriendListControllerMockRecorder is the mock recorder for MockFriendListController.
type MockFriendListControllerMockRecorder struct {
	mock *MockFriendListController
}

// NewMockFriendListController creates a new mock instance.
func NewMockFriendListController(ctrl *gomock.Controller) *MockFriendListController {
	mock := &MockFriendListController{ctrl: ctrl}
	mock.recorder = &MockFriendListControllerMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockFriendListController) EXPECT() *MockFriendListControllerMockRecorder {
	return m.recorder
}

// GetFriendListByUserId mocks base method.
func (m *MockFriendListController) GetFriendListByUserId(c echo.Context) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetFriendListByUserId", c)
	ret0, _ := ret[0].(error)
	return ret0
}

// GetFriendListByUserId indicates an expected call of GetFriendListByUserId.
func (mr *MockFriendListControllerMockRecorder) GetFriendListByUserId(c interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetFriendListByUserId", reflect.TypeOf((*MockFriendListController)(nil).GetFriendListByUserId), c)
}

// GetFriendListOfFriendsByUserId mocks base method.
func (m *MockFriendListController) GetFriendListOfFriendsByUserId(c echo.Context) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetFriendListOfFriendsByUserId", c)
	ret0, _ := ret[0].(error)
	return ret0
}

// GetFriendListOfFriendsByUserId indicates an expected call of GetFriendListOfFriendsByUserId.
func (mr *MockFriendListControllerMockRecorder) GetFriendListOfFriendsByUserId(c interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetFriendListOfFriendsByUserId", reflect.TypeOf((*MockFriendListController)(nil).GetFriendListOfFriendsByUserId), c)
}

// GetFriendListOfFriendsByUserIdWithPaging mocks base method.
func (m *MockFriendListController) GetFriendListOfFriendsByUserIdWithPaging(c echo.Context) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetFriendListOfFriendsByUserIdWithPaging", c)
	ret0, _ := ret[0].(error)
	return ret0
}

// GetFriendListOfFriendsByUserIdWithPaging indicates an expected call of GetFriendListOfFriendsByUserIdWithPaging.
func (mr *MockFriendListControllerMockRecorder) GetFriendListOfFriendsByUserIdWithPaging(c interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetFriendListOfFriendsByUserIdWithPaging", reflect.TypeOf((*MockFriendListController)(nil).GetFriendListOfFriendsByUserIdWithPaging), c)
}

// PostUserLink mocks base method.
func (m *MockFriendListController) PostUserLink(c echo.Context) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "PostUserLink", c)
	ret0, _ := ret[0].(error)
	return ret0
}

// PostUserLink indicates an expected call of PostUserLink.
func (mr *MockFriendListControllerMockRecorder) PostUserLink(c interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "PostUserLink", reflect.TypeOf((*MockFriendListController)(nil).PostUserLink), c)
}
